#!/usr/bin/env python3
"""Compare _publicationlist/refs.yml with _data/publications/refs.yml and show differences."""

import argparse
import shutil
import yaml

parser = argparse.ArgumentParser(description="Compare two refs.yml files and show new/removed entries.")
parser.add_argument("source", nargs="?", default="../_publicationlist/refs.yml",
                    help="Source refs.yml (generated by publicationlist make)")
parser.add_argument("target", nargs="?", default="../_data/publications/refs.yml",
                    help="Target refs.yml (used by the website)")
parser.add_argument("--sync", action="store_true",
                    help="Copy source to target when differences are found")
args = parser.parse_args()

with open(args.source) as f:
    source = yaml.safe_load(f)
with open(args.target) as f:
    target = yaml.safe_load(f)

source_keys = set(source.get("entries", {}).keys())
target_keys = set(target.get("entries", {}).keys())

new_keys = source_keys - target_keys
removed_keys = target_keys - source_keys

if new_keys:
    print("New entries in source (not yet in target):")
    for k in sorted(new_keys):
        entry = source["entries"][k]
        venue = entry.get("journal", entry.get("booktitle", "(no venue)"))
        print(f"  {k}: {venue}")
else:
    print("No new entries.")

if removed_keys:
    print("Entries removed from source (still in target):")
    for k in sorted(removed_keys):
        print(f"  {k}")

if not new_keys and not removed_keys:
    print("Files are in sync.")
elif args.sync:
    shutil.copy(args.source, args.target)
    print(f"\nSynced: {args.source} → {args.target}")
